# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - a_controller
    - g_controller

  a_controller:
    type: FollowJointTrajectory
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
  g_controller:
    type: FollowJointTrajectory
    joints:
      - Joint7Gripper